---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 123.
--- DateTime: 2022/10/15 15:56
---



---分布式锁
---Redis中使用hash结构存储
---key 锁的唯一标识，多个线程可以同时争抢同一把锁
---field 线程的唯一标识，保证一把锁只能被同一个线程重入，并且解锁时，只能解锁当前线程持有的锁
---value 锁冲入次数
---
local key = KEYS[1]

local threadFlag = ARGV[1]

local expire = ARGV[2]

if (redis.call('exists',key) == 0) then
    --- 不存在
    redis.call('hset',key,threadFlag,1)
    --- 刷新过期时间
    redis.call('expire',key,expire)
    return 1
end
--- 已经存在
if(redis.call('hexists',key,threadFlag) == 1) then
    --- 是同一个线程
    redis.call("hincrby",key,threadFlag,1)
    redis.call("expire",key,expire)
    return 1
end
return 0