---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 123.
--- DateTime: 2022/10/15 16:16
--- 可重入的分布式锁的解锁

local key = KEYS[1]

local threadFlag = ARGV[1]

local expire = ARGV[2]

--- 判断Redis中的锁是否是当前线程的锁
if redis.call("hexists",key,threadFlag) == 0 then
    --- Redis中的锁不是当前线程的锁
    return nil
end
--- 获取锁重入次数
local count = redis.call("hget",key,threadFlag)

if count == 1 then
    redis.call("del",key)
    return nil
end
redis.call("hset",key,threadFlag,count - 1)
redis.call("expire",key,expire)
return nil