---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 123.
--- DateTime: 2022/10/14 16:26

--- 获取Redis中锁的标识
local id = redis.call("get",KEYS[1])

--- 判断Redis中锁的标识与当前线程持有锁的标识是否一致
if id == ARGV[1] then
    redis.call("del",KEYS[1])
end
return
